In [1]:
with open("../dataset/text_dataset.txt") as dataset:
    text = dataset.read()
print(text[:1000])


April

April (Apr.) is the fourth month of the year in the Julian and Gregorian calendars, and comes between March and May. It is one of four months to have 30 days.

April always begins on the same day of the week as July, and additionally, January in leap years. April always ends on the same day of the week as December.

April comes between March and May, making it the fourth month of the year. It also comes first in the year out of the four months that have 30 days, as June, September and November are later in the year.

April begins on the same day of the week as July every year and on the same day of the week as January in leap years. April ends on the same day of the week as December every year, as each other's last days are exactly 35 weeks (245 days) apart.

In common years, April starts on the same day of the week as October of the previous year, and in leap years, May of the previous year. In common years, April finishes on the same day of the week as July of the previous ye

In [3]:
len(text)

178255102

In [4]:
text = text[:1500000]

In [5]:
chars = sorted(set(text))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !"$%&'()*+,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz|~ £®°±²³´·¹ÁÅÆÖ×Øàáâãäåæçèéêìíîïðñòóôö÷øúüÿāēĕěīıłōūǐǔǫəɪʻʼʿˇˈˊˋΓΔΛΜάέήίαβγδεζηθικλμνοπρςστυφωόύابجرشلهἀἄἡἥἶ‎–—‘’“”†…⁄€ℓ℠™⅟→−♄♆のㄌㄑㄒㄓㄕㄘㄚㄢㄣㄤㄧㄨㄩ万中元八區圆國大姬子宵市村民汤燕爷百神縣華蓟财轄都鄉鄰里鎮饺마히
263


In [6]:
string_to_integer = {ch:i for i, ch in enumerate(chars)}
integer_to_string = {i:ch for i, ch in enumerate(chars)}
def encode(string) : 
    return [string_to_integer[c] for c in string]
def decode(liste):
    return "".join(integer_to_string[i] for i in liste)
print(encode("Hello World"))
print(decode(encode("Hello World")))


[39, 67, 74, 74, 77, 1, 54, 77, 80, 74, 66]
Hello World


In [8]:
import torch
data = torch.tensor(encode(text), dtype = torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([1500000]) torch.int64
tensor([ 0, 32, 78, 80, 71, 74,  0,  0, 32, 78, 80, 71, 74,  1,  8, 32, 78, 80,
        14,  9,  1, 71, 81,  1, 82, 70, 67,  1, 68, 77, 83, 80, 82, 70,  1, 75,
        77, 76, 82, 70,  1, 77, 68,  1, 82, 70, 67,  1, 87, 67, 63, 80,  1, 71,
        76,  1, 82, 70, 67,  1, 41, 83, 74, 71, 63, 76,  1, 63, 76, 66,  1, 38,
        80, 67, 69, 77, 80, 71, 63, 76,  1, 65, 63, 74, 67, 76, 66, 63, 80, 81,
        12,  1, 63, 76, 66,  1, 65, 77, 75, 67, 81,  1, 64, 67, 82, 85, 67, 67,
        76,  1, 44, 63, 80, 65, 70,  1, 63, 76, 66,  1, 44, 63, 87, 14,  1, 40,
        82,  1, 71, 81,  1, 77, 76, 67,  1, 77, 68,  1, 68, 77, 83, 80,  1, 75,
        77, 76, 82, 70, 81,  1, 82, 77,  1, 70, 63, 84, 67,  1, 19, 16,  1, 66,
        63, 87, 81, 14,  0,  0, 32, 78, 80, 71, 74,  1, 63, 74, 85, 63, 87, 81,
         1, 64, 67, 69, 71, 76, 81,  1, 77, 76,  1, 82, 70, 67,  1, 81, 63, 75,
        67,  1, 66, 63, 87,  1, 77, 68,  1, 82, 70, 67,  1, 85, 67, 67, 73,  1,
      

In [10]:
n = int(0.9*len(data))
train_data = data[:n] # TODO Improve because the data is heterogenous
val_data = data[n:]

In [11]:
block_size = 8
train_data[:block_size+1]

tensor([ 0, 32, 78, 80, 71, 74,  0,  0, 32])

In [13]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"When context is {context}, target is {target}")

When context is tensor([0]), target is 32
When context is tensor([ 0, 32]), target is 78
When context is tensor([ 0, 32, 78]), target is 80
When context is tensor([ 0, 32, 78, 80]), target is 71
When context is tensor([ 0, 32, 78, 80, 71]), target is 74
When context is tensor([ 0, 32, 78, 80, 71, 74]), target is 0
When context is tensor([ 0, 32, 78, 80, 71, 74,  0]), target is 0
When context is tensor([ 0, 32, 78, 80, 71, 74,  0,  0]), target is 32


In [14]:
torch.manual_seed(42)
batch_size = 4
block_size = 8
def get_batch(split):
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data)-block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+1+block_size] for i in ix])
    return x, y
xb, yb = get_batch("train")
print(xb)
print(yb)

tensor([[ 66,  71,  65,  82,  63,  82,  77,  80],
        [ 81,  65,  71,  67,  76,  65,  67,  12],
        [ 76,  83,  75,  64,  67,  80,  81,   1],
        [ 67,  80,  76,  63,  64,  67, 130,   1]])
tensor([[ 71,  65,  82,  63,  82,  77,  80,   1],
        [ 65,  71,  67,  76,  65,  67,  12,   1],
        [ 83,  75,  64,  67,  80,  81,   1,  85],
        [ 80,  76,  63,  64,  67, 130,   1,  50]])


In [33]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(42)

class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        # (Batch, Block_size) for the idx, as well of target (B,T)
        logits = self.token_embedding_table(idx) # (B,T,C) (Batch, Block_size, Vocab_size) in output - each token get a list of proba for the next token (a row of the embedding table)
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits  = logits.view(B*T, C)
            targets = targets.view(B*T)

            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:,-1,:] # Becomes (B, C)
            probs = F.softmax(logits, dim=-1) # (B, C) with proba
            idx_next = torch.multinomial(probs, num_samples=1) # Sample the next token (B, 1)
            idx = torch.cat((idx, idx_next), dim=1) # Append next, to do it again (B, T+1)
        return idx

    
m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape, loss)
print(decode(m.generate(torch.zeros((1,1), dtype= torch.long), 100)[0].tolist()))


torch.Size([32, 263]) tensor(6.1234, grad_fn=<NllLossBackward0>)

Å燕子Y鎮神→b ‎νR‘ㄧI± ²Λ财,ό-轄*DY國R(/njφʼãå5β"öλ汤Å6øέτ八qmfpωb>ʿĕο+神ä마ℓ³pπ_ήhNɪ姬αuς ω
ñτبç℠]80Æu<%ē:ύ财‘3Yåb


In [34]:
optimizer = torch.optim.Adam(m.parameters(), lr = 1e-3)

In [45]:
batch_size=32
for steps in range(10000):
    xb, yb = get_batch("train")

    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    if steps%1000 == 0:
        print(loss.item())

2.6332590579986572
2.3765060901641846
2.6210367679595947
2.5240418910980225
2.502375364303589
2.465149164199829
2.621765613555908
2.3987908363342285
2.4389233589172363
2.5924699306488037


In [60]:
print(decode(m.generate(torch.zeros((1,1), dtype= torch.long), 500)[0].tolist()))





Indre Miane alap'st, micly st (" ROر/ne.
Apllerbicome Inagewe he canowe la irre Orypr th tongld m Ped oty ote are ce Chand lsoscernteliethace anis s, we Incorobr Pobarast the e icha teald therkit eripllthefol Mooplan bet Mon bypa ethorve fer s ooplente florue orer t Jasig BPon plintorelaltas waleromall t ttro Thenel Soping aws) wan. buseise wes.

Aley ame thowayade, plen. thas g ontainti on benging Condun, itogle uconaint rye thes es adory f t peverindutherurtcesinedus ) teound corndise mend i
